In [1]:
import pandas as pd
import geopandas as gpd
from shapely.geometry import MultiPolygon

In [2]:
kreise = 'C:/Users/david/OneDrive/02_Uni/02_Master/05_Masterarbeit/03_MATSim/01_prep/02_vg250/vg250_neu/VG250_KRS.shp'

In [3]:
gdf_kreise = gpd.read_file(kreise)
gdf_kreise['raw'] = gdf_kreise.apply(lambda x:
                                     x['geometry'] if x['geometry'].type == 'MultiPolygon' else
                                     MultiPolygon([x['geometry']]),
                                     axis=1)

In [4]:
gdf_kreise = gdf_kreise.to_crs(epsg=25832)
gdf_kreise.columns = gdf_kreise.columns.map(str.lower)

In [5]:
gdf_kreise.head(3)

,ade,gf,bsg,ars,ags,sdv_ars,gen,bez,ibz,bem,...,nuts,ars_0,ags_0,wsk,debkg_id,rs,sdv_rs,rs_0,geometry,raw
0,4,4,1,01001,01001,010010000000,Flensburg,Kreisfreie Stadt,40,--,...,DEF01,010010000000,01001000,2008-01-01,DEBKGDL20000002R,01001,010010000000,010010000000,"POLYGON ((526513.753 6075133.412, 526547.941 6...",(POLYGON ((3526591.850410001 6077123.906686103...
1,4,4,1,01002,01002,010020000000,Kiel,Kreisfreie Stadt,40,--,...,DEF02,010020000000,01002000,2006-01-01,DEBKGDL20000E43X,01002,010020000000,010020000000,"POLYGON ((575841.569 6032148.032, 575869.668 6...",(POLYGON ((3575940.275965828 6034122.503407862...
2,4,4,1,01003,01003,010030000000,Lübeck,Kreisfreie Stadt,40,--,...,DEF03,010030000000,01003000,2006-02-01,DEBKGDL20000DYM9,01003,010030000000,010030000000,"POLYGON ((623056.151 5983746.445, 623191.574 5...",(POLYGON ((3623175.006806144 5985702.682303936...