In [13]:
import pandas as pd
import geopandas as gpd
from shapely.geometry import LineString

# Read-In data

In [14]:
stops = "C:/Users/david/OneDrive/02_Uni/02_Master/05_Masterarbeit/01_Text/04_Abbildungen/Kapitel_4/google_transit/stops.txt"
shapes = "C:/Users/david/OneDrive/02_Uni/02_Master/05_Masterarbeit/01_Text/04_Abbildungen/Kapitel_4/google_transit/shapes.txt"
trips = "C:/Users/david/OneDrive/02_Uni/02_Master/05_Masterarbeit/01_Text/04_Abbildungen/Kapitel_4/google_transit/trips.txt"
routes = "C:/Users/david/OneDrive/02_Uni/02_Master/05_Masterarbeit/01_Text/04_Abbildungen/Kapitel_4/google_transit/routes.txt"

In [15]:
df_stops = pd.read_csv(stops)
df_shapes = pd.read_csv(shapes)
df_trips = pd.read_csv(trips)
df_routes = pd.read_csv(routes)

In [16]:
df_stops.head(3)

            stop_id  stop_name   stop_lat  stop_lon
0  de:08111:100:1:1  Stammheim  48.850046  9.156174
1  de:08111:100:2:3  Stammheim  48.849443  9.156022
2  de:08111:100:2:4  Stammheim  48.850217  9.156093

In [17]:
df_shapes.head(3)

,shape_id,shape_pt_lat,shape_pt_lon,shape_pt_sequence,shape_dist_traveled
0,10-12-j21-1.1.H,48.806804,9.525427,1,0.00
1,10-12-j21-1.1.H,48.806196,9.523318,2,168.63
2,10-12-j21-1.1.H,48.805813,9.522288,3,255.25

In [18]:
df_trips.head(3)

,route_id,service_id,trip_id,shape_id,trip_headsign,direction_id,block_id
0,10-12-j21-1,T0#10,100.T0.10-12-j21-1.13.R,10-12-j21-1.13.R,Schorndorf,1,NaN
1,10-12-j21-1,T0#10,11.T0.10-12-j21-1.6.H,10-12-j21-1.6.H,Esslingen (N),0,NaN
2,10-12-j21-1,T0#10,13.T0.10-12-j21-1.6.H,10-12-j21-1.6.H,Esslingen (N),0,NaN

In [19]:
df_routes.head(3)

,route_id,agency_id,route_short_name,route_long_name,route_type,route_color,route_text_color
0,10-12-j21-1,NaN,S12,Schorndorf - Bad Cannstatt - Esslingen,109,83b23b,FFFFFF
1,10-15-j21-1,NaN,S15,Bietigheim - Feuerbach - Vaihingen - Herrenberg,109,83b23b,FFFFFF
2,10-15-j21-2,NaN,S15,Bietigheim - Feuerbach - Vaihingen - Herrenberg,109,83b23b,FFFFFF

# Create shapes

In [20]:
gdf_shapes = gpd.GeoDataFrame(
    df_shapes, geometry=gpd.points_from_xy(df_shapes.shape_pt_lon, df_shapes.shape_pt_lat))

gdf_lines = gdf_shapes.dissolve(by='shape_id').reset_index(drop=False)
gdf_lines = gdf_lines[['shape_id', 'geometry']]
gdf_lines['geometry'] = gdf_lines['geometry'].apply(lambda x: LineString(x))

In [21]:
gdf_lines.head(3)

          shape_id                                           geometry
0   10-1-j21-1.1.H  LINESTRING (9.10464 48.74838, 9.10466 48.74876...
1  10-1-j21-1.10.R  LINESTRING (9.15655 48.77009, 9.15798 48.77046...
2  10-1-j21-1.11.R  LINESTRING (9.00456 48.68792, 9.00551 48.68845...

# Merge

In [22]:
gdf_trips = df_trips.merge(gdf_lines, how ='left')
gdf_trips = gdf_trips.merge(df_routes, how = 'left')

In [28]:
gdf_trips = gpd.GeoDataFrame(
    gdf_trips.drop(columns=['geometry']), geometry=gdf_trips['geometry'])

In [35]:
gdf_trips = gdf_trips[['route_short_name', 'route_type', 'route_color', 'geometry']]
gdf_trips = gdf_trips[gdf_trips['geometry'] != None]

AttributeError: 'NoneType' object has no attribute '_geom'

In [37]:
gdf_lines = gdf_trips.dissolve('route_short_name')

      route_short_name  route_type route_color geometry
17832               S8           2      8f908f     None
17833               S8           2      8f908f     None
17834               S8           2      8f908f     None
17885               S8           2      8f908f     None
17886               S8           2      8f908f     None
17887               S8           2      8f908f     None
17888               S8           2      8f908f     None
17939               S8           2      8f908f     None
18092              RE8           2      8f908f     None
18093              RE8           2      8f908f     None
18094              RE8           2      8f908f     None
18095              RE8           2      8f908f     None
18096              RE8           2      8f908f     None
18097              RE8           2      8f908f     None
18098              RE8           2      8f908f     None
18099              RE8           2      8f908f     None
18100              RE8           2      8f908f     None
18151              RE8           2      8f908f     None
18152              RE8           2      8f908f     None
18153              RE8           2      8f908f     None
18193              RE8           2      8f908f     None
18194              RE8           2      8f908f     None
18195              RE8           2      8f908f     None
18264              RE8           2      8f908f     None
18265              RE8           2      8f908f     None
18266              RE8           2      8f908f     None
18267              RE8           2      8f908f     None
18268              RE8           2      8f908f     None
18269              RE8           2      8f908f     None
18343              RE8           2      8f908f     None
18344              RE8           2      8f908f     None
18345              RE8           2      8f908f     None
18346              RE8           2      8f908f     None
18347              RE8           2      8f908f     None
18348              RE8           2      8f908f     None
18393              RE8           2      8f908f     None
18394              RE8           2      8f908f     None
18395              RE8           2      8f908f     None
18480              RE8           2      8f908f     None
18481              RE8           2      8f908f     None
18482              RE8           2      8f908f     None
18483              RE8           2      8f908f     None
18484              RE8           2      8f908f     None
18485              RE8           2      8f908f     None
18486              RE8           2      8f908f     None
18487              RE8           2      8f908f     None
18488              RE8           2      8f908f     None
18637             RE90           2      8f908f     None
18648             RE90           2      8f908f     None
18682             RE90           2      8f908f     None
18684             RE90           2      8f908f     None
53459              161           3      FF0000     None

In [ ]:
gdf_lines.head(3)